---
dist: xenial
language: python
python: 3.7
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
notifications:
  email:
    recipients:
      - hello@codeforiati.org
    on_success: change
    on_failure: always
script: pytest --split-report --template=templates/index.html --report=_site/index.html
after_script: .travis/push.sh
