title: IATI Status
description: Monitoring the status of live IATI services and websites.

plugins:
  - jekyll-feed
  - jekyll-redirect-from

feed:
  excerpt_only: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      redirect_to: /

exclude:
  - /venv/
  - CNAME
  - Gemfile
  - Gemfile.lock
