name: CI
on:
  push:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: report
        path: report.json
  commit:
    name: Commit result
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/checkout@v1
    - uses: technote-space/workflow-conclusion-action@v2
    - name: Download an artifact
      uses: actions/download-artifact@v2
      with:
        name: report
    - name: Commit result
      run: |
        cp tmpl/img/${{ env.WORKFLOW_CONCLUSION }}.svg status.svg
        cp tmpl/md/${{ env.WORKFLOW_CONCLUSION }}.md latest.md

        # setup git
        git config --global user.email "57559326+codeforIATIbot@users.noreply.github.com"
        git config --global user.name "Code for IATI bot"

        # clone the gh-pages branch into /gh-pages/
        git clone --branch gh-pages https://${{ secrets.TOKEN }}@github.com/codeforIATI/iati-status.git gh-pages

        # move the generated report into place
        mv report.json gh-pages/_data/`date +"%Y-%m-%d"`.json
        mv status.svg gh-pages
        mv latest.md gh-pages/_posts/`date +"%Y-%m-%d"`-index.md

        # commit and push
        cd gh-pages
        git add .
        git commit --message "Github actions build: ${{ github.run_number }}"
        git push

        # clean up
        cd ..
        rm -rf gh-pages
